### ISSUE TITLE
[sympy] 式の解消における変数の条件について

### ISSUE THREAD

**Issue by TKNRK** [TKNRK/Hosobe#12]
sympyの式の計算において変数に条件をつけることは可能なのでしょうか？
例えば、E = (e1,e2,e3) のような sympy.Matrix の変数があって、このベクトル変数が常に正規であると仮定されている時、E.dot(E) = (e1)**2 +(e2)**2 +(e3)**2 ではなく E.dot(E) = 1 のように出力してくれる機能とかを探します。

**Comment by TKNRK** [comment]
memo:
sympy.refine
sympy.Q.orthogonal
sympy.matrices.expressions.matmul.remove_ids

**Comment by wakita** [comment]
これは未解決なんですか？

**Comment by TKNRK** [comment]
解決してました。

**Comment by wakita** [comment]
だけど、`remove_ids` はきたないので、以下を参考にして下さい。

```
with assuming(Q.orthogonal(A), Q.orthogonal(B)):
   refine(refine((A * B).T * (A * B)).doit())
```
